name: Build and test

on: workflow_dispatch

jobs:
  lint:
    name: Lint
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e pep8
        
  unit-test:
    name: Unit tests
    runs-on: Ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run Unit Tests
        run: tox -e py3

  build:
    name: Build the charm
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: 5.20/stable
      - name: Build charm
        id: builder
        run:
          sudo snap install charmcraft --classic
          charmcraft pack -v


