name: Build and test
on: workflow_dispatch
jobs:
  unit-test:
    name: Unit tests
    runs-on: Ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run Unit Tests
        run: tox -e py3


