name: Run tests

on: workflow_dispatch

jobs:
  lint:
    name: Lint
    runs-on: Ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run linters
        run: tox -e lint
        
  unit-test:
    name: Unit tests
    runs-on: Ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: python -m pip install tox
      - name: Run Unit Tests
        run: tox -e unit
